services:
  - type: web
    runtime: node
    name: mercatino-usato
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
    disk:
      name: mercatino-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
